dist: xenial
language: ruby
rvm: 2.6.3
gemfile:
  - Gemfile
  - test/gemfiles/rails52.gemfile
  - test/gemfiles/rails51.gemfile
  - test/gemfiles/rails50.gemfile
before_install:
  - export LIBSODIUM_VERSION=1.0.17
  - ./test/ci/install_libsodium.sh
  - export LD_LIBRARY_PATH=$HOME/libsodium/$LIBSODIUM_VERSION/lib:$LD_LIBRARY_PATH
cache:
  directories:
    - $HOME/libsodium
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
