dist: bionic
language: ruby
rvm: 2.6
services:
  - mongodb
gemfile:
  - Gemfile
  - test/gemfiles/rails52.gemfile
  - test/gemfiles/rails51.gemfile
  - test/gemfiles/rails50.gemfile
addons:
  apt:
    packages:
      - libsodium23
script: bundle exec rake test
notifications:
  email:
    on_success: never
    on_failure: change
